### ISSUE TITLE
Template para facturas

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/argentina-reporting#17]
Estimados, no se como ofrecer un commit para este repositorio, pero llevo trabajando un tiempo con este archivo reportes que tiene la posibilidad para que el cliente pueda firmar las facturas impresas. Lo comparto para ver si lo pueden incluir ya que creo que puede servirle a más de uno. Aprovecho también para comentar que el archivo tiene un pequeño arreglo con el tema de los decimales, algo que comenté en otra oportunidad. En mi caso utilizamos 3 decimales para las cantidades en los productos, para aquellos que utilizan 2 o más decimales también funciona.
[einvoice_with_footer_signature.odt.zip](https://github.com/ingadhoc/argentina-reporting/files/1844933/einvoice_with_footer_signature.odt.zip)

**Comment by jjscarafia** [comment]
Buenas Adrian,
gracias por el issue. Podrás detallarme un caso donde lo de los digits arregle el error de decimales? Más que nada para entenderlo y ver si ese fix es el que conviene. 
Podes usar esta base de demo para probarlo y replicarlo si querés: http://02030-9-0-25cf8f.runbot.adhoc.com.ar/?db=02030-9-0-25cf8f-all (admin / admin para entrar)
