### ISSUE TITLE
[?] QWeb reports instead of Aeroo reports

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/argentina-reporting#18]
Subo este issue acá, pero aplica para los otros repo también.

Como sugerencia, para que lo evalúen a futuro, se podría contemplar reemplazar los reportes de Aeroo por reportes QWeb, o bien incorporarlos como alternativa opcional.

Estos, además de usar el reporting engine nativo de odoo, permiten una mejor customización por el usuario a través de la extensión de vistas o incorporación de hojas de estilo css.

Tienen como desventaja, claro, que su edición es un poco más complicada para quienes no conocen HTML.

**Comment by jjscarafia** [comment]
Buenas Ivan, completamente de acuerdo en que sería mejor técnicamente. Ahora bien, además de lo más complejo y menos user friendly para usuarios funcionales es el tema con las imagenes de fondo y demás que hasta donde sé no van muy bien en qweb/html en general. En nuestro caso los clientes personalizan el fondo de los reportes y se le incrusta de fondo a los informes en aeroo quedando bastante bien.

Igualmente me parece bien sumarlo, al menos, como alternativa. De nuestor lado no va a ser prioridad para la migración a v11, tal vez si para v12. Pero si llegas a querer incorporar algún que otro reporte qweb, bienvenido sea :)

**Comment by jjscarafia** [comment]
ya estaría en v13
