### ISSUE TITLE
Need dependencies for l10n_ar_aeroo_base

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/argentina-reporting#3]
Unknown dependencies for l10n_ar_aeroo_base named report_custom_filename that should be in patches or reporting-engine modules

Found at OCA repository to satisfy that need
https://github.com/OCA/reporting-engine/tree/9.0/report_custom_filename

**Comment by jjscarafia** [comment]
added here https://github.com/ingadhoc/argentina-reporting/blob/9.0/oca_dependencies.txt
Thanks for reporting!

**Comment by SBollatti** [comment]
report-print-send?
Isn't it report_custom_filename?
Conflict between https://github.com/OCA/reporting-engine.git (this one has the report_custom_filename) https://github.com/ingadhoc/reporting-engine.git (this one doesn't has it)

**Comment by jjscarafia** [comment]
Fixed now, reporting-engine has report_custom_filename
