### ISSUE TITLE
Al instalar el modulo l10n_ar_aeroo_payment_group: excepción con traceback vacío

### ISSUE THREAD

**Issue by Danisan** [ingadhoc/argentina-reporting#66]
Pasos para reproducir:
1) instalar l10n_ar_aeroo_payment_group
2) Ingresar al menú: "facturación/clientes/recibos de clientes
- se obtiene un traceback vacío.
- en el log se puede ver un error que dice:
res.partner(7067,) has no member named "receivable_debt_ids"

**Comment by jjscarafia** [comment]
closed with https://github.com/ingadhoc/argentina-reporting/pull/67
